name: workflowrename
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: yahooo
      - run: |
          ls -a
          echo ""
          git branch -a